# Generated by Django 5.1.6 on 2026-04-12 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cvdata_payment_userprofile_delete_user_payment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvdata',
            name='structured_profile',
            field=models.JSONField(default=dict, help_text='Structured profile data extracted from CV: skills, experience, seniority, etc.'),
        ),
        migrations.CreateModel(
            name='CVLinkPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('public_with_expiry', 'Public with Expiry'), ('private_tokenized', 'Private with Token')], default='public_with_expiry', max_length=50)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('access_token', models.CharField(blank=True, db_index=True, max_length=255)),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link_policy', to='api.cvdata')),
            ],
            options={
                'verbose_name': 'CV Link Policy',
                'verbose_name_plural': 'CV Link Policies',
            },
        ),
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('seniority', models.CharField(blank=True, max_length=50)),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('skills', models.JSONField(default=list, help_text='List of normalized skills')),
                ('industries', models.JSONField(default=list)),
                ('locations', models.JSONField(default=list, help_text='Preferred work locations')),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('languages', models.JSONField(default=list)),
                ('remote_preference', models.CharField(blank=True, max_length=50)),
                ('extracted_at', models.DateTimeField(auto_now=True)),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI extraction confidence')),
                ('cv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_profiles', to='api.cvdata')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_profile', to='api.userprofile')),
            ],
            options={
                'verbose_name': 'Job Profile',
                'verbose_name_plural': 'Job Profiles',
            },
        ),
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('cv_publish', 'CV Publishing'), ('premium_template', 'Premium Template Access'), ('job_search', 'Job Search Access')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlements', to='api.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='api.userprofile')),
            ],
            options={
                'verbose_name': 'Entitlement',
                'verbose_name_plural': 'Entitlements',
                'unique_together': {('user', 'feature', 'is_active')},
            },
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='Job ID from external source', max_length=255)),
                ('source', models.CharField(help_text='Job board source (LinkedIn, Indeed, etc.)', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('salary', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('match_score', models.FloatField(help_text='0-100 match score')),
                ('match_reasons', models.JSONField(default=list, help_text='Why this job matches')),
                ('status', models.CharField(choices=[('new', 'New'), ('viewed', 'Viewed'), ('saved', 'Saved'), ('applied', 'Applied'), ('dismissed', 'Dismissed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='api.jobprofile')),
            ],
            options={
                'verbose_name': 'Job Match',
                'verbose_name_plural': 'Job Matches',
                'ordering': ['-match_score', '-created_at'],
                'unique_together': {('job_profile', 'external_id')},
            },
        ),
    ]
