# Generated by Django 5.1.6 on 2026-08-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvdata',
            name='category',
            field=models.CharField(blank=True, choices=[('digitale-it', 'Digitale & IT'), ('ingegneri-tecnici', 'Ingegneri & Tecnici'), ('sanitari-assistenziali', 'Sanitari & Assistenziali'), ('commerciale-vendita', 'Commerciale & Vendita'), ('amministrative-finanziarie', 'Amministrative & Finanziarie'), ('logistica', 'Logistica')], default='', help_text="Area professionale scelta dall'utente: determina le sezioni mostrate sulla pagina pubblica.", max_length=40),
        ),
        migrations.AddField(
            model_name='cvdata',
            name='show_services_pricing',
            field=models.BooleanField(default=True, help_text='Mostra le sezioni Servizi/Tariffe nella pagina pubblica (tipico per liberi professionisti).'),
        ),
        migrations.AddField(
            model_name='cvdata',
            name='target_positions',
            field=models.CharField(blank=True, default='', help_text='Posizioni lavorative che il CV vuole ricoprire (separate da virgola).', max_length=500),
        ),
    ]
