# Generated by Django 5.1.6 on 2026-08-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cvdata_category_cvdata_show_services_pricing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvdata',
            name='show_services_pricing',
        ),
        migrations.AddField(
            model_name='cvdata',
            name='show_pricing',
            field=models.BooleanField(default=True, help_text="Mostra la sezione Tariffe/Pricing nella pagina pubblica. La sezione Servizi, invece, viene mostrata automaticamente ogni volta che ci sono dati (non serve un flag: anche un dipendente puo' descrivere i servizi/competenze offerte, ma non tutti vendono pacchetti a prezzo fisso)."),
        ),
    ]
